### ISSUE TITLE
TSAN and ASAN files a spammed with messages about missing gcda files

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/JenkinsConfiguration#6]
There are many messages about missing gcda files in some ASAN builds, which make up 90 % of the console output and make it very hard to see what's going on.
```
< profiling: /scratch/build-ChimeraTK-DeviceAccess/CMakeFiles/ChimeraTK-DeviceAccess.dir/device_backends/LogicalNameMapping/src/LNMBackendVariableAccessor.cc.gcda: cannot open: No such file or directory
```
However, these files are only needed for code coverage analysis, which are not run in any of those modes (only in the Debug run).

ASAN is compiled with -O0 --coverage and even should have the gcda files

**Comment by killenb** [comment]
It seems even if the sanitiser does not find any other issues this makes the test fail. See CommandLineTools-Analysis for instance.

**Comment by phako** [comment]
Needs https://github.com/ChimeraTK/project-template/commit/2ca77c561e08e5b773358c2c794a864784490a2f
